pos1-posmode       =kinematic
pos1-frequency     =l1
pos1-soltype        =backward
pos1-elmask        =17
pos1-dynamics      =on
pos1-ionoopt       =brdc
pos1-tropopt       =saas
pos1-navsys        =5

pos2-armode        =fix-and-hold
pos2-arthres       =2.5
pos2-arminfix      =5
pos2-maxage        =2.0

ant2-antdelu       =1.800

out-solformat      =llh
out-outhead        =on
out-outopt         =on
out-timesys        =gpst
out-timeform       =hms
out-timendec       =3
out-degform        =deg
out-height         =ellipsoidal
pos2-gloarmode=on

out-outstat        =residual
