pos1-posmode       =static
pos1-frequency     =l1
pos1-soltype       =combined
pos1-elmask        =15
pos1-dynamics      =off
pos1-ionoopt       =brdc
pos1-tropopt       =saas
pos1-navsys        =5

pos2-armode        =fix-and-hold
pos2-arthres       =3.0
pos2-maxage        =30

ant2-antdelu       =1.800

out-solformat      =llh
out-outhead        =on
out-outopt         =on
out-timesys        =gpst
out-timeform       =hms
out-timendec       =3
out-degform        =deg
out-height         =ellipsoidal
out-outstat        =residual
